### ISSUE TITLE
Provide a parameter to customize vcpkg version to use?

### ISSUE THREAD

**Issue by Lord-Kamina** [johnwason/vcpkg-action#1]
I just found this action out of frustration with `run-vcpkg` and its constant unnecessary rebuilds.
It took me a while to set-up properly mostly because I'm not the one in my team who regularly uses either vcpkg or YAML but I eventually got it right, I think.

However, since yesterday I was experiencing a consistent error with `boost-build`; today, with a fresh head I realized it's a regression in vcpkg, which could be fixed by going back to the last release or an earlier commit.

I think this option would likely be trivial to add (it's probably just a parameter you gotta then pass-on to the `checkout` action?), but it would likely make a lot of people's lives easier.

**Comment by johnwason** [comment]
Closed with #2

**Comment by johnwason** [comment]
Thanks @Lord-Kamina
