### ISSUE TITLE
Process completed with exit code 1.

### ISSUE THREAD

**Issue by lumynou5** [johnwason/vcpkg-action#12]
Sorry, I'm not familiar with GitHub Actions.
I'm trying to test the code automatically, but I got an error. I really don't understand what's wrong or what did I miss.

The workflow:
https://github.com/Luminous-Coder/merak16-asm/actions/runs/3853277885/jobs/6566120064

**Comment by johnwason** [comment]
You will need to also specify a `triplet` option. See the examples in the readme.
