### ISSUE TITLE
The packages are built twice in manifest mode

### ISSUE THREAD

**Issue by netheril96** [johnwason/vcpkg-action#19]
The YAML config is [here](https://github.com/netheril96/securefs/blob/62a70e236fe8e2210ac35a4ae3bfd1d9f042c10b/.github/workflows/ccpp.yml), and the build script referenced is [here](https://github.com/netheril96/securefs/blob/62a70e236fe8e2210ac35a4ae3bfd1d9f042c10b/build.py). When [built on GitHub Actions](https://github.com/netheril96/securefs/actions/runs/5218523533/jobs/9419396340), all the packages are built twice, once in `vcpkg build` step, and once in my own `build` step. When I try it on my own machine, they are built only once. What could be the cause and fix?

**Comment by johnwason** [comment]
Take a look at https://github.com/johnwason/vcpkg-action/issues/14#issuecomment-1558312751

**Comment by netheril96** [comment]
That looks like a different bug. I do intend that it uses manifest mode.

**Comment by johnwason** [comment]
There are two possible solutions:

* vcpkg will search for vcpkg.json int he parent directory of the build. If it finds one, it will ignore the previously built packages. Check the source code out in a subdirectory and build in a different tree, or if you are using setup.py make sure it is building outside of the source tree.
* The arguments provided by this action during manifest build are `--x-manifest-root=${{ inputs.manifest-dir }} --x-install-root=${{ github.workspace }}/vcpkg/installed`. You need to pass `${{ steps.vcpkg.outputs.vcpkg-cmake-config }}` to cmake configure to capture these extra arguments to avoid rebuilds.

The other option is to set the `export VCPKG_DEFAULT_BINARY_CACHE=${{ github.workspace }}/vcpkg_cache` environmental variable. This will still 'build' the packages, but in reality it will just extract the previously built ones. This option has the benefit of not requiring any workarounds.

**Comment by netheril96** [comment]
It works: https://github.com/netheril96/securefs/actions/runs/5223160611/jobs/9429641749

I added env expressions: https://github.com/netheril96/securefs/commit/bf06cc69258b6f6e8964775c65de083b7c3ab664

The issue is resolved for me, but I suggest that you add this to the documentation because others might have the same need.
