### ISSUE TITLE
Using a community triplet

### ISSUE THREAD

**Issue by MangaD** [johnwason/vcpkg-action#20]
Hello! 

I would like to use a custom triplet, provided here: https://github.com/Neumann-A/my-vcpkg-triplets.git

How can I accomplish this?

**Comment by johnwason** [comment]
Hi @MangaD 

To use the community triplet, you can clone the repository into your workspace. Then, use the `extra-args` parameter to `vcpkg-action` to pass the `--overlay-triplets` path. You can use `{{ github.workspace }}` variable to get the absolute path of the workspace.

**Comment by MangaD** [comment]
Thank you, it is working!
