### ISSUE TITLE
error: In manifest mode, `vcpkg install` does not support individual package arguments.

### ISSUE THREAD

**Issue by xiaoyifang** [johnwason/vcpkg-action#27]
configuration like this:
```
- name: vcpkg build
  uses: johnwason/vcpkg-action@v6
  id: vcpkg
  with:
    pkgs: breakpad
    triplet: x64-windows-release
    token: ${{ github.token }}
    github-binarycache: true
```

**there is a vcpkg.json file in the workspace dir.**

got 

error:
```
error: In manifest mode, `vcpkg install` does not support individual package arguments.
To install additional packages, edit vcpkg.json and then run `vcpkg install` without any package arguments.
See https://learn.microsoft.com/vcpkg/users/manifests for more information.
Using manifest file at D:\a\goldendict-ng\goldendict-ng\vcpkg.json.
```

**Comment by johnwason** [comment]
I think this is expected behavior when using manifest mode. You specify the packages you want in the `vcpkg.json` file rather than on the command line.

**Comment by xiaoyifang** [comment]
The point here is that when there is a vcpkg.json file in the workspace .  `vcpkg install pkg` will not work any more.
Any way this should be a vcpkg issue.  I'll close this.

**Comment by johnwason** [comment]
Oh, I see. If you want to ignore the vcpkg.json manifest, use actions/checkout with a subdirectory and build out of tree. It should be ignored.
