### ISSUE TITLE
Cache build result

### ISSUE THREAD

**Issue by laper32** [johnwason/vcpkg-action#5]
Hi, thanks for your action. It pretty fit my cases!

However, if possible, could you please cache package build results?

For example, if we have built boost, and nothing changed, then we could cache all binaries file we have built to avoid build multiple times.

**Comment by johnwason** [comment]
I am not sure what you mean? The packages built by vcpkg are cached and should restore next run if there aren't any updates.

**Comment by laper32** [comment]
That's strange, my private project uses nearly an hour for building, even though I didn't change anything of these packages.
And when I test on another project, looks like it works correctly.
I will keep on tracking what happened, and when I found anything news, I will open a new issue for further update.
Closing for nothing found for now.
